baseURL = "https://hsmint.github.io/"
languageCode = "en-us"
title = "HSMINT's BLOG"
theme = "liva-hugo"
enableEmoji = false
paginate = 6
disqusShortname = "hsmints-blog"
googleAnalitycsID = "UA-171554028-1"

[markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"

  # JS Plugins
  #[[params.plugins.js]]
  #URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

#################### default parameters ################################
[params]
logo = "images/hsmint.png"
home = "Home"
author = "HSMINT"
description = "A Blog of Hsmint"

#################### Copy Rights ################################
# copyright
copyright = "| copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://wwww.facebook.com/hsmint"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://www.github.com/hsmint"
